services:
  freguesia-web:
    build: .
    container_name: api-freguesia-web
    restart: always
    expose:
      - "5000"  # Exponha a porta internamente para o Nginx
    volumes:
      - "./:/freguesia-web/"
    command: bash -c "gunicorn -w 2 -b 0.0.0.0:5000 app.main:app --timeout 200"
    mem_limit: 250m
    cpus: 1

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    depends_on:
      - freguesia-web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    mem_limit: 250m
    cpus: 1