services:
  freguesia-web:
    build: .
    container_name: api-freguesia-web
    restart: always
    ports:
      - 80:5000
    volumes:
      - "./:/freguesia-web/"
    command: bash -c "gunicorn -b 0.0.0.0:5000 app.main:app --timeout 300"